comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

CODECOV_TOKEN="02592712-f8c1-43c7-92fb-c3b44a9e62df"